[package]
name = "nexfile_desktop_app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "nexfile_desktop_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
apalis = { version = "1.0.0-rc.9", default-features = false, features = ["limit"] }
apalis-sqlite = { git = "https://github.com/apalis-dev/apalis-sqlite.git", rev = "f49ea2ddb00ad8f0d7986e45a2d575c73849066a", default-features = false, features = [
  "tokio-comp",
  "migrate",
  "json",
  "chrono",
] }
futures = "0.3"
nanoid = "0.4"
sqlx = { version = "0.9.0", default-features = false, features = [
  "runtime-tokio",
  "sqlite",
  "macros",
  "migrate",
] }
sysinfo = { version = "0.39.6", default-features = false, features = ["disk"] }
uuid = { version = "1", features = ["v4"] }
image = { version = "0.25", default-features = false, features = ["bmp", "gif", "ico", "jpeg", "png", "tiff", "webp"] }
avif-decode = "1.0.2"
heif-oxide = "0.1.0"
ndarray = "0.17"
ort = "=2.0.0-rc.12"
resvg = "0.48.1"
thiserror = "2"
tokenizers = { version = "0.22", default-features = false, features = ["onig"] }
tauri-plugin-dialog = "2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_IO",
  "Win32_System_Ioctl",
] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
image = { version = "0.25", default-features = false, features = ["avif"] }
