import { useState } from "react";

import { Popover } from "radix-ui";
import { Check, ChevronDown, Search, Shapes } from "lucide-react";

export function ModelCategoryFilter({ categories, selected, onSelect }: { categories: string[]; selected?: string; onSelect: (value?: string) => void }) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const matches = categories.filter(value => value.toLowerCase().includes(query.trim().toLowerCase()));
  const choose = (value?: string) => { onSelect(value); setOpen(false); };
  return <Popover.Root open={open} onOpenChange={value => { setOpen(value); setQuery(""); }}>
    <Popover.Trigger asChild><button type="button" className={`collection-filter-trigger${selected ? " active" : ""}`} aria-label={`Model category: ${selected ?? "All categories"}`} title="Categories generated by the processing model"><Shapes size={16}/><span>{selected ?? "All categories"}</span><ChevronDown size={14}/></button></Popover.Trigger>
    <Popover.Portal><Popover.Content className="collection-filter-menu" align="end" sideOffset={8} collisionPadding={12} aria-label="Model-generated categories">
      <p className="model-category-label">Model-generated categories</p>
      <div className="collection-filter-search"><Search size={16}/><input aria-label="Search categories" placeholder="Search categories…" value={query} onChange={event => setQuery(event.target.value)}/></div>
      <div className="collection-filter-options">
        <button type="button" aria-pressed={!selected} onClick={() => choose()}><Shapes size={16}/><span>All categories</span>{!selected && <Check size={15}/>}</button>
          {matches.map(value => <button type="button" key={value} aria-pressed={selected === value} onClick={() => choose(value)}><Shapes size={16}/><span>{value}</span>{selected === value && <Check size={15}/>}</button>)}
          {!matches.length && <p>{categories.length ? "No matching categories." : "Categories appear after files are processed."}</p>}

      </div>
    </Popover.Content></Popover.Portal>
  </Popover.Root>;
}

